/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Clinic;

import Business.DateUtils;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Patient.Assessment;
import Business.Patient.Patient;
import Business.Patient.PatientRequestStatus;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientEvaluationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tarun
 */
public class PatientHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientHistoryJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private PatientEvaluationWorkRequest patientEvaluationWorkRequest;
    private EcoSystem system;
    private Patient patient;

    public PatientHistoryJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.patient = patient;
        setFields();
        populateAssessmentHistory();
        setSize(1200,1200);
    }

    private void setFields() {
        lblpatientName.setText(patient.getPatientname());
        lbladdress.setText(patient.getAddress());
        lblage.setText(String.valueOf(patient.getAge()));
        lblcity.setText(patient.getCity());
        lblgender.setText(patient.getGender());
        lblstate.setText(patient.getState());
        lblstatus.setText(patient.getMartialstatus());
        lbldate.setText(DateUtils.dateToString(patient.getRegisterationdate()));
        ComboBoxPatientName.addItem(patient.getPatientname());
    }

    public void populateAssessmentHistory() {
        DefaultTableModel model = (DefaultTableModel) tblAssessmentHistory.getModel();

        model.setRowCount(0);
        for (Assessment assessment : patient.getAssessments()) {
            Object[] row = new Object[6];
            row[0] = DateUtils.dateToString(assessment.getCreatedDate());
            row[1] = assessment;
            UserAccount doctor = assessment.getDoctor();
            if (doctor != null) {
                row[2] = doctor.getFirstName();
            } else {
                row[2] = "N/A";
            }
            UserAccount counsellor = assessment.getCounsellor();
            if (counsellor != null) {
                row[3] = counsellor.getFirstName();
            } else {
                row[3] = "N/A";
            }
            row[4] = assessment.getScore();
            row[5] = assessment.getZone();

            model.addRow(row);
        }
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        detailsJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblpatientName = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        assessmentJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssessmentHistory = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxPatientName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Patient Name:");

        jLabel4.setText("Patient Address:");

        jLabel5.setText("Marital Status:");

        jLabel8.setText("City :");

        jLabel9.setText("State:");

        jLabel11.setText("Gender:");

        jLabel12.setText("Age:");

        lblpatientName.setText("jLabel3");

        lbladdress.setText("jLabel6");

        lblstatus.setText("jLabel7");

        lblcity.setText("jLabel13");

        lblstate.setText("jLabel14");

        lblgender.setText("jLabel15");

        lblage.setText("jLabel16");

        jLabel17.setText("Registration Date:");

        lbldate.setText("jLabel18");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Patient History");

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsJPanelLayout = new javax.swing.GroupLayout(detailsJPanel);
        detailsJPanel.setLayout(detailsJPanelLayout);
        detailsJPanelLayout.setHorizontalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel3))
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsJPanelLayout.createSequentialGroup()
                                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbladdress)
                                    .addComponent(lblpatientName)
                                    .addComponent(lbldate)
                                    .addComponent(lblstatus))
                                .addGap(120, 120, 120)
                                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(83, 83, 83)
                                        .addComponent(lblcity))
                                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(67, 67, 67)
                                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblgender, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblage, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblstate, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        detailsJPanelLayout.setVerticalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(lbldate))
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblcity))
                        .addGap(41, 41, 41)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblstate))
                        .addGap(38, 38, 38)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblgender)))
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblpatientName))
                        .addGap(40, 40, 40)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbladdress))
                        .addGap(33, 33, 33)
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblstatus)
                            .addComponent(jLabel12)
                            .addComponent(lblage))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(140, 140, 140))
        );

        jTabbedPane1.addTab("Details ", detailsJPanel);

        tblAssessmentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assessment Date", "Nurse Name", "Doctor Name", "Counsellor Name", "Score", "Zone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAssessmentHistory);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Assessment History");

        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout assessmentJPanelLayout = new javax.swing.GroupLayout(assessmentJPanel);
        assessmentJPanel.setLayout(assessmentJPanelLayout);
        assessmentJPanelLayout.setHorizontalGroup(
            assessmentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentJPanelLayout.createSequentialGroup()
                .addGroup(assessmentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assessmentJPanelLayout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(viewButton))
                    .addGroup(assessmentJPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(assessmentJPanelLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        assessmentJPanelLayout.setVerticalGroup(
            assessmentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assessmentJPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(viewButton)
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("Assessment History", assessmentJPanel);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Patient History");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Patient Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(ComboBoxPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(392, 392, 392))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblAssessmentHistory.getSelectedRow();

        if (selectedrow >= 0) {
            Assessment request = (Assessment)tblAssessmentHistory.getValueAt(selectedrow, 1);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            PatientAssessmentDetailJPanel counselorAssessmentJPanel = new PatientAssessmentDetailJPanel(userProcessContainer, userAccount, enterprise, patient, request);
            userProcessContainer.add("CounselorPatientHistoryJPanel", counselorAssessmentJPanel);
            layout.next(userProcessContainer);

        } else {
            JOptionPane.showMessageDialog(null, " Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_viewButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxPatientName;
    private javax.swing.JPanel assessmentJPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel detailsJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblpatientName;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable tblAssessmentHistory;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
