/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Clinic;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Patient.Assessment;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientEvaluationWorkRequest;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author Dipti
 */
public class PatientAssessmentDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientAssessmentDetailJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private PatientEvaluationWorkRequest patientEvaluationWorkRequest;
    private Assessment assessment;
    private Patient patient;

    PatientAssessmentDetailJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Patient patient, Assessment assessment) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.assessment = assessment;
        this.patient = patient;
        initComponents();
        setSize(1200, 1200);

        answer1.setText(assessment.getQuestionAnswer().get(1).get(1));
        answer2.setText(assessment.getQuestionAnswer().get(2).get(1));
        answer3.setText(assessment.getQuestionAnswer().get(3).get(1));
        answer4.setText(assessment.getQuestionAnswer().get(4).get(1));
        answer5.setText(assessment.getQuestionAnswer().get(5).get(1));
        answer6.setText(assessment.getQuestionAnswer().get(6).get(1));
        answer7.setText(assessment.getQuestionAnswer().get(7).get(1));
        answer8.setText(assessment.getQuestionAnswer().get(8).get(1));
        answer9.setText(assessment.getQuestionAnswer().get(9).get(1));
        answer10.setText(assessment.getQuestionAnswer().get(10).get(1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        answer1 = new javax.swing.JLabel();
        answer2 = new javax.swing.JLabel();
        answer3 = new javax.swing.JLabel();
        answer4 = new javax.swing.JLabel();
        answer5 = new javax.swing.JLabel();
        answer6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        answer7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        answer8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        answer9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        answer10 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Assessment Detail");

        jLabel7.setText(" 1. How often do you have a drink containing alcohol ?");

        jLabel8.setText(" 2. How many drinks containing alcohol do you have on a typical day when you are drinking?");

        jLabel9.setText(" 3. How often do you have 6* or more drinks on one occassion ?");

        jLabel10.setText(" 4. How often during the last year have you found that you were not able to stop drinking once you had started? ");

        jLabel2.setText(" 5. How often during the last year have you failed to do what was normally expected from you because of drinking ?");

        jLabel3.setText(" 6. How often during the past year have needed a first drink in the morning to get yourself going after a heavy night of drinking ?");

        answer1.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer1.setText("<value>");

        answer2.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer2.setText("<value>");

        answer3.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer3.setText("<value>");

        answer4.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer4.setText("<value>");

        answer5.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer5.setText("<value>");

        answer6.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer6.setText("<value>");

        jLabel15.setText(" 7. How often during the last year have you felt guilt or remorse after drinking ?");

        answer7.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer7.setText("<value>");

        jLabel17.setText(" 8. How often during the past year have you been unable to remember what happened the night before because you were drinking ?");

        answer8.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer8.setText("<value>");

        jLabel19.setText(" 9. Have you or someone else been injured as a result of your drinking?");

        answer9.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer9.setText("<value>");

        jLabel21.setText(" 10. Has a relative or a  friend or a doctor or  health worker been concerned about your drinking or suggeseted you cut down ?");

        answer10.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        answer10.setText("<value>");

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(backButton)
                .addGap(519, 519, 519))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answer10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(answer1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(answer2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(answer3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(answer4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(answer5))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(answer6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(answer7))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(answer8))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(answer9))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(answer10))
                .addGap(25, 25, 25)
                .addComponent(backButton)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer1;
    private javax.swing.JLabel answer10;
    private javax.swing.JLabel answer2;
    private javax.swing.JLabel answer3;
    private javax.swing.JLabel answer4;
    private javax.swing.JLabel answer5;
    private javax.swing.JLabel answer6;
    private javax.swing.JLabel answer7;
    private javax.swing.JLabel answer8;
    private javax.swing.JLabel answer9;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
